services:
  manager-service:
    build:
      context: manager-service
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - impl5-stage
      - impl5-stage2

  stage:
    build:
      context: stage
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8082"
    ports:
      - "8082:8082"

  stage2:
    build:
      context: stage2
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8083"
    ports:
      - "8083:8083"
