services:
  impl5-manager-service:
    build:
      context: impl5-manager-service
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - impl5-stage

  impl5-stage:
    build:
      context: impl5-stage
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8082"
    ports:
      - "8082:8082"
