version: '3'

services:
  impl1-and-2:
    build:
      context: impl1-and-2
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8080"
    ports:
      - "8080:8080"

  impl5-manager-service:
    build:
      context: impl5-manager-service
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8081"
    ports:
      - "8081:8081"

  impl5-source:
    build:
      context: impl5-source
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8082"
    ports:
      - "8082:8082"
    depends_on:
      - impl5-manager-service

  impl5-stage:
    build:
      context: impl5-sink
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8083"
    ports:
      - "8083:8083"
    depends_on:
      - impl5-manager-service

  impl5-sink:
    build:
      context: impl5-sink
      dockerfile: src/main/docker/Dockerfile.jvm
    expose:
      - "8084"
    ports:
      - "8084:8084"
    depends_on:
      - impl5-manager-service
